version: "3.9"
services:
  db:
    container_name: crypton-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - crypton-db-data:/var/lib/postgresql/data
      - ./api/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: crypton-api
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - type: bind
        source: ./api/src
        target: /api/src

  front:
    container_name: crypton-front
    build: ./front
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    volumes:
      - type: bind
        source: ./front/src
        target: /front/src
        
volumes:
  crypton-db-data:
